services:
  db:
    image: postgres:15-alpine
    container_name: videoflix_database
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: videoflix_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    environment:
      - DJANGO_EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
    container_name: videoflix_backend

    volumes:
      - ./core:/app/core
      - ./user_auth_app:/app/user_auth_app
      - ./videoflix_app:/app/videoflix_app
      - ./manage.py:/app/manage.py
      - ./backend.entrypoint.sh:/app/backend.entrypoint.sh
      - ./media:/app/media
      - videoflix_static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db 
      - redis 


volumes:
  postgres_data:
  redis_data:
  # videoflix_media:
  videoflix_static:
