# Generated by Django 5.2.4 on 2025-10-13 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=500)),
                ('video_file', models.FileField(blank=True, max_length=500, null=True, upload_to='videos/')),
                ('hls_master', models.FileField(blank=True, max_length=500, null=True, upload_to='videos/')),
                ('trailer', models.FileField(blank=True, max_length=500, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='videos/')),
                ('category', models.CharField(default='General', max_length=50)),
            ],
        ),
    ]
