# Generated by Django 5.2.4 on 2025-10-19 18:35

import datetime
import videoflix_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('video_file', models.FileField(blank=True, max_length=500, null=True, upload_to=videoflix_app.models.video_upload_path)),
                ('category', models.CharField(default='General', max_length=50)),
                ('hls_master', models.FileField(blank=True, max_length=500, null=True, upload_to='video/hls')),
                ('trailer', models.FileField(blank=True, max_length=500, null=True, upload_to='video/trailer')),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='video/')),
            ],
        ),
    ]
