# Generated by Django 5.2.4 on 2025-09-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0003_video_category_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
