# Generated by Django 5.1.4 on 2025-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0004_video_hls_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_dir',
        ),
        migrations.AddField(
            model_name='video',
            name='hls_master',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
