# Generated by Django 5.2.6 on 2025-09-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0005_remove_video_hls_dir_video_hls_master_video_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_master',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='videos/'),
        ),
    ]
