# Generated by Django 5.2.6 on 2025-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0006_alter_video_hls_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='trailer',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='videos/'),
        ),
    ]
